# Generated by Django 3.0.3 on 2020-05-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('houseid', models.AutoField(primary_key=True, serialize=False)),
                ('housename', models.CharField(max_length=50)),
                ('short_leasing', models.BooleanField(default=False)),
                ('short_leasing_fee', models.IntegerField(blank=True, null=True)),
                ('long_leasing', models.BooleanField(default=False)),
                ('long_leasing_fee', models.IntegerField(blank=True, null=True)),
                ('house_type', models.IntegerField(blank=True, choices=[(0, '单人间'), (1, '双人间'), (2, '四人间')], null=True, verbose_name='房间类型')),
                ('district', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, default='未知', max_length=15, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='house_photo/', verbose_name='照片')),
            ],
            options={
                'ordering': ['houseid'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(choices=[(0, '申请中'), (1, '已通过')], verbose_name='审核状态')),
                ('active_code', models.CharField(max_length=20, verbose_name='验证码')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
