# Generated by Django 3.0.3 on 2020-06-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('house_id', models.IntegerField()),
                ('is_allowed', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('allowed_by', models.CharField(max_length=10)),
                ('rent_type', models.CharField(max_length=10)),
                ('s_y', models.IntegerField()),
                ('s_m', models.IntegerField()),
                ('s_d', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'ordering': ['apply_id'],
            },
        ),
        migrations.CreateModel(
            name='Customerserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=50)),
                ('short_leasing', models.BooleanField(default=False)),
                ('short_leasing_fee', models.IntegerField(blank=True, null=True)),
                ('long_leasing', models.BooleanField(default=False)),
                ('long_leasing_fee', models.IntegerField(blank=True, null=True)),
                ('house_type', models.IntegerField(blank=True, choices=[(0, '单人间'), (1, '双人间'), (2, '四人间')], null=True, verbose_name='房间类型')),
                ('district', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, default='未知', max_length=15, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='demo1/', verbose_name='照片')),
                ('pic_num', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, '申请中'), (1, '已出租'), (2, '空闲')], default=2, verbose_name='审核状态')),
            ],
            options={
                'ordering': ['house_id'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('house_id', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['message_id'],
            },
        ),
        migrations.CreateModel(
            name='MyMessage',
            fields=[
                ('my_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('context', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=10)),
                ('receiver', models.CharField(max_length=10)),
                ('status', models.IntegerField(choices=[(0, '已读'), (1, '未读')], verbose_name='阅读状态')),
            ],
            options={
                'ordering': ['my_message_id'],
            },
        ),
        migrations.CreateModel(
            name='Repairing',
            fields=[
                ('repair_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('house_id', models.IntegerField()),
                ('is_allow', models.BooleanField(default=False)),
                ('is_fix', models.BooleanField(default=False)),
                ('repair_technician', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='demo1/', verbose_name='照片')),
                ('pic_num', models.IntegerField(default=0)),
                ('comment', models.IntegerField(choices=[(0, '不满意'), (1, '不太满意'), (2, '基本满意'), (3, '十分满意'), (4, '未评价')], default=4, verbose_name='评价')),
            ],
            options={
                'ordering': ['repair_id'],
            },
        ),
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('apply_id', models.IntegerField()),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='demo1/', verbose_name='照片')),
                ('pic_num', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(0, '待处理'), (1, '已处理')], default=0, verbose_name='处理状态')),
                ('handled_by', models.CharField(blank=True, max_length=10, null=True)),
                ('handled_content', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['report_id'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('contact_number', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('real_name', models.CharField(max_length=15)),
                ('ID_card', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(choices=[(0, '申请中'), (1, '已通过')], verbose_name='审核状态')),
                ('active_code', models.CharField(max_length=20, verbose_name='验证码')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
